export enum ErrorCode {
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    BAD_REQUEST = 'BAD_REQUEST',
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
    NOT_FOUND = 'NOT_FOUND',
    ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND',
    TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
    
    // Auth & Identity
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
    USERNAME_ALREADY_TAKEN = 'USERNAME_ALREADY_TAKEN',
    EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
    INVALID_OTP = 'INVALID_OTP',
    OTP_EXPIRED = 'OTP_EXPIRED',
    PASSWORD_CHANGED = 'PASSWORD_CHANGED',
    
    // Conversations & Messages
    CONVERSATION_NOT_FOUND = 'CONVERSATION_NOT_FOUND',
    CANNOT_CHAT_WITH_SELF = 'CANNOT_CHAT_WITH_SELF',
    NOT_GROUP_MEMBER = 'NOT_GROUP_MEMBER',
    NOT_GROUP_ADMIN = 'NOT_GROUP_ADMIN',
    ALREADY_GROUP_MEMBER = 'ALREADY_GROUP_MEMBER',
    ADMIN_CANNOT_REMOVE_SELF = 'ADMIN_CANNOT_REMOVE_SELF',
    MESSAGE_NOT_FOUND = 'MESSAGE_NOT_FOUND',
    CANNOT_DELETE_MESSAGE = 'CANNOT_DELETE_MESSAGE',
    
    // Media & Storage
    NO_FILE_UPLOADED = 'NO_FILE_UPLOADED',
    INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',
    FILE_TOO_LARGE = 'FILE_TOO_LARGE',
    UPLOAD_FAILED = 'UPLOAD_FAILED'
}
